CREATE DATABASE IF NOT EXISTS book_db;
CREATE DATABASE IF NOT EXISTS cart_db;
CREATE DATABASE IF NOT EXISTS catalog_db;
CREATE DATABASE IF NOT EXISTS comment_rate_db;
CREATE DATABASE IF NOT EXISTS recommender_db;
